version: "3.9"

services:
  # webアプリケーションのコンテナ
  app:
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile
      target: php83
    volumes:
      - ./backend:/var/www
    working_dir: /var/www

  # webサーバーのコンテナ
  web:
    build:
      context: .
      dockerfile: ./infra/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./backend:/var/www

  # dbサーバーのコンテナ
  db:
    build:
      context: .
      dockerfile: ./infra/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: output_project
      MYSQL_USER: output_project_user
      MYSQL_PASSWORD: output_project_password
      MYSQL_ROOT_PASSWORD: output_project_password
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - output-project-db-volume:/var/lib/mysql

volumes:
  output-project-db-volume:
