version: "3.9"

services:
  # webアプリケーションのコンテナ
  backend:
    build:
      context: .
      dockerfile: ./infra/backend/Dockerfile
      target: php83
    volumes:
      - ./backend:/var/www/backend
    working_dir: /var/www/backend

  # webサーバーのコンテナ
  web:
    build:
      context: .
      dockerfile: ./infra/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./backend:/var/www/backend

  # frontendアプリケーションのコンテナ
  frontend:
    build:
      context: .
      dockerfile: ./infra/frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/frontend
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # dbサーバーのコンテナ
  db:
    build:
      context: .
      dockerfile: ./infra/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: output_project
      MYSQL_USER: output_project_user
      MYSQL_PASSWORD: output_project_password
      MYSQL_ROOT_PASSWORD: output_project_password
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - output-project-db-volume:/var/lib/mysql

volumes:
  output-project-db-volume:
